In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
path = r"C:\Users\Noble Adike\Desktop\Coding\KPMG\kpmg-1a\data\harvard\Year 2 (Jun 2023 - May 2024)\BTU_GEO_hourly\48190951_BTU_GEO_hourly.csv"
df_main = pd.read_csv(path)

In [3]:
df_main.head()

,Timestamp,BTU2(Gwell_L)_ReturnT (F),BTU2(Gwell_L)_SupplyT (F),BTU3(Gwell_R)_ReturnT (F),BTU3(Gwell_R)_SupplyT (F),BTU4(Gwell_Com)_ReturnT (F),BTU4(Gwell_Com)_SupplyT (F),BTU2(Gwell_L)_energy (BTUs),BTU2(Gwell_L)_flow (GPM),BTU3(Gwell_R)_energy (BTUs),BTU3(Gwell_R)_flow (GPM),BTU4(Gwell_Com)_energy (BTUs),BTU4(Gwell_Com)_flow (GPM)
0,2023-06-01 00:00:00-04:00,72.581100,65.445774,72.555957,65.668384,74.150368,69.931212,0.021125,2.203907,0.013875,2.311148,0.009318,4.455836
1,2023-06-01 01:00:00-04:00,69.112625,61.939153,69.200549,62.406544,69.112919,62.169351,0.021125,5.259304,0.013875,5.539413,0.009318,10.590311
2,2023-06-01 02:00:00-04:00,68.582014,63.046914,68.660200,63.377885,68.557709,63.227161,0.021125,5.258770,0.013875,5.536645,0.009318,10.598287
3,2023-06-01 03:00:00-04:00,68.100715,63.249014,68.172012,63.540485,68.054279,63.415703,0.021125,5.261022,0.013875,5.542987,0.009318,10.605865
4,2023-06-01 04:00:00-04:00,67.681953,63.250703,67.747969,63.532216,67.620039,63.415262,0.021125,5.260647,0.013875,5.540667,0.009318,10.601623

In [9]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Timestamp                      8760 non-null   object
 1   BTU2(Gwell_L)_ReturnT (F)      8760 non-null   float64
 2   BTU2(Gwell_L)_SupplyT (F)      8760 non-null   float64
 3   BTU3(Gwell_R)_ReturnT (F)      8760 non-null   float64
 4   BTU3(Gwell_R)_SupplyT (F)      8760 non-null   float64
 5   BTU4(Gwell_Com)_ReturnT (F)    8760 non-null   float64
 6   BTU4(Gwell_Com)_SupplyT (F)    8760 non-null   float64
 7   BTU2(Gwell_L)_energy (BTUs)    8760 non-null   float64
 8   BTU2(Gwell_L)_flow (GPM)       8760 non-null   float64
 9   BTU3(Gwell_R)_energy (BTUs)    8760 non-null   float64
 10  BTU3(Gwell_R)_flow (GPM)       8760 non-null   float64
 11  BTU4(Gwell_Com)_energy (BTUs)  8760 non-null   float64
 12  BTU4(Gwell_Com)_flow (GPM)     8760 non-null   float64
dtypes: float64(12), object(1)
memory usage: 889.8+ KB

In [4]:
df_main.isna().sum()

Timestamp                        0
BTU2(Gwell_L)_ReturnT (F)        0
BTU2(Gwell_L)_SupplyT (F)        0
BTU3(Gwell_R)_ReturnT (F)        0
BTU3(Gwell_R)_SupplyT (F)        0
BTU4(Gwell_Com)_ReturnT (F)      0
BTU4(Gwell_Com)_SupplyT (F)      0
BTU2(Gwell_L)_energy (BTUs)      0
BTU2(Gwell_L)_flow (GPM)         0
BTU3(Gwell_R)_energy (BTUs)      0
BTU3(Gwell_R)_flow (GPM)         0
BTU4(Gwell_Com)_energy (BTUs)    0
BTU4(Gwell_Com)_flow (GPM)       0
dtype: int64

In [13]:
df_main.value_counts().sum()

np.int64(8760)

In [5]:
zero_counts = (df_main == 0).sum()
zero_counts

Timestamp                           0
BTU2(Gwell_L)_ReturnT (F)           0
BTU2(Gwell_L)_SupplyT (F)           0
BTU3(Gwell_R)_ReturnT (F)           0
BTU3(Gwell_R)_SupplyT (F)           0
BTU4(Gwell_Com)_ReturnT (F)         0
BTU4(Gwell_Com)_SupplyT (F)         0
BTU2(Gwell_L)_energy (BTUs)      4050
BTU2(Gwell_L)_flow (GPM)         4047
BTU3(Gwell_R)_energy (BTUs)      4050
BTU3(Gwell_R)_flow (GPM)         4049
BTU4(Gwell_Com)_energy (BTUs)    3847
BTU4(Gwell_Com)_flow (GPM)       3998
dtype: int64

In [6]:
df_main['Timestamp'] = pd.to_datetime(df_main['Timestamp'])

C:\Users\Noble Adike\AppData\Local\Temp\ipykernel_3132\569357206.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df_main['Timestamp'] = pd.to_datetime(df_main['Timestamp'])

In [7]:
df_main.head()

,Timestamp,BTU2(Gwell_L)_ReturnT (F),BTU2(Gwell_L)_SupplyT (F),BTU3(Gwell_R)_ReturnT (F),BTU3(Gwell_R)_SupplyT (F),BTU4(Gwell_Com)_ReturnT (F),BTU4(Gwell_Com)_SupplyT (F),BTU2(Gwell_L)_energy (BTUs),BTU2(Gwell_L)_flow (GPM),BTU3(Gwell_R)_energy (BTUs),BTU3(Gwell_R)_flow (GPM),BTU4(Gwell_Com)_energy (BTUs),BTU4(Gwell_Com)_flow (GPM)
0,2023-06-01 00:00:00-04:00,72.581100,65.445774,72.555957,65.668384,74.150368,69.931212,0.021125,2.203907,0.013875,2.311148,0.009318,4.455836
1,2023-06-01 01:00:00-04:00,69.112625,61.939153,69.200549,62.406544,69.112919,62.169351,0.021125,5.259304,0.013875,5.539413,0.009318,10.590311
2,2023-06-01 02:00:00-04:00,68.582014,63.046914,68.660200,63.377885,68.557709,63.227161,0.021125,5.258770,0.013875,5.536645,0.009318,10.598287
3,2023-06-01 03:00:00-04:00,68.100715,63.249014,68.172012,63.540485,68.054279,63.415703,0.021125,5.261022,0.013875,5.542987,0.009318,10.605865
4,2023-06-01 04:00:00-04:00,67.681953,63.250703,67.747969,63.532216,67.620039,63.415262,0.021125,5.260647,0.013875,5.540667,0.009318,10.601623

In [8]:
df_main = df_main.set_index('Timestamp')

In [21]:
df_main

,BTU2(Gwell_L)_ReturnT (F),BTU2(Gwell_L)_SupplyT (F),BTU3(Gwell_R)_ReturnT (F),BTU3(Gwell_R)_SupplyT (F),BTU4(Gwell_Com)_ReturnT (F),BTU4(Gwell_Com)_SupplyT (F),BTU2(Gwell_L)_energy (BTUs),BTU2(Gwell_L)_flow (GPM),BTU3(Gwell_R)_energy (BTUs),BTU3(Gwell_R)_flow (GPM),BTU4(Gwell_Com)_energy (BTUs),BTU4(Gwell_Com)_flow (GPM)
Timestamp,,,,,,,,,,,,
2022-06-01 00:00:00-04:00,75.040726,70.522681,74.785046,70.368942,78.455754,79.778523,0.0,0.0,0.0,0.0,0.000579,0.001995
2022-06-01 01:00:00-04:00,74.656820,70.058893,74.418943,69.915249,77.989847,79.297036,0.0,0.0,0.0,0.0,0.000000,0.000000
2022-06-01 02:00:00-04:00,74.357355,69.788286,74.115027,69.660119,77.602630,78.886805,0.0,0.0,0.0,0.0,0.000000,0.000000
2022-06-01 03:00:00-04:00,74.360408,70.194095,74.091848,70.112857,77.500555,78.777793,0.0,0.0,0.0,0.0,0.000000,0.000000
2022-06-01 04:00:00-04:00,74.470037,70.652708,74.208688,70.614932,77.518523,78.772827,0.0,0.0,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
2023-05-31 19:00:00-04:00,73.439383,69.975626,73.347141,69.946995,76.520778,77.328809,0.0,0.0,0.0,0.0,0.000000,0.000000
2023-05-31 20:00:00-04:00,73.540788,70.044299,73.433754,70.007668,76.616079,77.426735,0.0,0.0,0.0,0.0,0.000000,0.000000
2023-05-31 21:00:00-04:00,73.629954,70.101324,73.506638,70.068226,76.679861,77.480990,0.0,0.0,0.0,0.0,0.000000,0.000000
2023-05-31 22:00:00-04:00,73.668879,70.138545,73.551542,70.102510,76.694057,77.494696,0.0,0.0,0.0,0.0,0.000000,0.000000
2023-05-31 23:00:00-04:00,73.676779,70.161604,73.557531,70.125401,76.670259,77.466775,0.0,0.0,0.0,0.0,0.000000,0.000000

In [9]:
temp_cols = [
    "BTU2(Gwell_L)_ReturnT (F)", "BTU2(Gwell_L)_SupplyT (F)",
    "BTU3(Gwell_R)_ReturnT (F)", "BTU3(Gwell_R)_SupplyT (F)",
    "BTU4(Gwell_Com)_ReturnT (F)", "BTU4(Gwell_Com)_SupplyT (F)"
]

energy_cols = [
    "BTU2(Gwell_L)_energy (BTUs)",
    "BTU3(Gwell_R)_energy (BTUs)",
    "BTU4(Gwell_Com)_energy (BTUs)"
]

flow_cols = [
    "BTU2(Gwell_L)_flow (GPM)",
    "BTU3(Gwell_R)_flow (GPM)",
    "BTU4(Gwell_Com)_flow (GPM)"
]

In [10]:
for col in df_main.columns:
    if col in temp_cols:
        df_main.loc[((df_main[col] < 40) | (df_main[col] > 120)), col] = np.nan

In [11]:
for col in df_main.columns:
    if col in energy_cols or col in temp_cols:
        df_main.loc[df_main[col] < 0, col] = np.nan

In [12]:
df_main.isna().sum()

BTU2(Gwell_L)_ReturnT (F)        0
BTU2(Gwell_L)_SupplyT (F)        0
BTU3(Gwell_R)_ReturnT (F)        0
BTU3(Gwell_R)_SupplyT (F)        0
BTU4(Gwell_Com)_ReturnT (F)      4
BTU4(Gwell_Com)_SupplyT (F)      0
BTU2(Gwell_L)_energy (BTUs)      0
BTU2(Gwell_L)_flow (GPM)         0
BTU3(Gwell_R)_energy (BTUs)      0
BTU3(Gwell_R)_flow (GPM)         0
BTU4(Gwell_Com)_energy (BTUs)    0
BTU4(Gwell_Com)_flow (GPM)       0
dtype: int64

In [13]:
df_main = df_main.sort_index()

In [14]:
field = 'BTU4(Gwell_Com)_ReturnT (F)'
df_main[field] = df_main[field].interpolate(limit=2)

In [15]:
df_main.isna().sum()

BTU2(Gwell_L)_ReturnT (F)        0
BTU2(Gwell_L)_SupplyT (F)        0
BTU3(Gwell_R)_ReturnT (F)        0
BTU3(Gwell_R)_SupplyT (F)        0
BTU4(Gwell_Com)_ReturnT (F)      0
BTU4(Gwell_Com)_SupplyT (F)      0
BTU2(Gwell_L)_energy (BTUs)      0
BTU2(Gwell_L)_flow (GPM)         0
BTU3(Gwell_R)_energy (BTUs)      0
BTU3(Gwell_R)_flow (GPM)         0
BTU4(Gwell_Com)_energy (BTUs)    0
BTU4(Gwell_Com)_flow (GPM)       0
dtype: int64

In [16]:
scaler = StandardScaler()
df_scaled = df_main
df_scaled[temp_cols+energy_cols+flow_cols] = scaler.fit_transform(df_scaled[temp_cols + energy_cols + flow_cols])

In [17]:
df_scaled.head()

,BTU2(Gwell_L)_ReturnT (F),BTU2(Gwell_L)_SupplyT (F),BTU3(Gwell_R)_ReturnT (F),BTU3(Gwell_R)_SupplyT (F),BTU4(Gwell_Com)_ReturnT (F),BTU4(Gwell_Com)_SupplyT (F),BTU2(Gwell_L)_energy (BTUs),BTU2(Gwell_L)_flow (GPM),BTU3(Gwell_R)_energy (BTUs),BTU3(Gwell_R)_flow (GPM),BTU4(Gwell_Com)_energy (BTUs),BTU4(Gwell_Com)_flow (GPM)
Timestamp,,,,,,,,,,,,
2023-06-01 00:00:00-04:00,0.881448,0.435233,0.886518,0.455497,0.818863,0.455918,-0.814776,-0.096887,-0.899262,-0.091703,-0.929493,-0.095286
2023-06-01 01:00:00-04:00,0.554801,0.046241,0.576141,0.089734,0.414963,-0.199125,-0.814776,1.153287,-0.899262,1.168471,-0.929493,1.148535
2023-06-01 02:00:00-04:00,0.504830,0.169126,0.526159,0.198654,0.370447,-0.109854,-0.814776,1.153069,-0.899262,1.167391,-0.929493,1.150152
2023-06-01 03:00:00-04:00,0.459503,0.191545,0.481001,0.216887,0.330082,-0.093942,-0.814776,1.153991,-0.899262,1.169866,-0.929493,1.151688
2023-06-01 04:00:00-04:00,0.420066,0.191732,0.441777,0.215960,0.295265,-0.093980,-0.814776,1.153837,-0.899262,1.168961,-0.929493,1.150828