In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
path = r"C:\Users\Noble Adike\Desktop\Coding\KPMG\kpmg-1a\data\harvard\Year 2 (Jun 2023 - May 2024)\RH_hourly\48190912_RH_hourly.csv"
df = pd.read_csv(path)
df.head()

,Timestamp,Z11_RH (%),Z12+13_RH (%),Z15+16_RH (%),Z17_RH (%),Z1_RH (%),Z21_RH (%),Z22+23_RH (%),Z24_RH (%),Z25+26+27_RH (%),Z31_RH (%),Z32_RH (%),Z33_RH (%),Z3_RH (%),Z4_RH (%),Z5_RH (%)
0,2023-06-01 00:00:00-04:00,42.966667,39.757667,34.861666,35.256667,41.540000,43.620000,41.435999,38.725333,43.431999,34.285334,33.121667,36.718333,36.933333,36.951000,40.076333
1,2023-06-01 01:00:00-04:00,44.112000,40.085001,35.441666,35.333667,41.760667,43.799334,42.823334,39.976333,43.982001,34.097000,32.688000,36.674000,37.158000,37.120667,40.878667
2,2023-06-01 02:00:00-04:00,43.748000,39.457000,35.754333,35.562333,41.676667,42.754000,41.169667,38.132333,42.231999,34.507666,33.974333,37.484000,35.858667,37.092000,41.272667
3,2023-06-01 03:00:00-04:00,43.278666,39.045666,35.993667,35.521000,41.206667,43.832000,41.967667,37.425333,43.048000,34.779666,33.649333,37.121000,35.761333,37.033667,40.719667
4,2023-06-01 04:00:00-04:00,42.915999,38.785333,36.200000,35.540666,40.190001,43.331332,42.117333,37.212334,42.993334,34.903667,33.632000,37.043333,35.786667,37.063667,40.464000

In [3]:
df.describe()

,Z11_RH (%),Z12+13_RH (%),Z15+16_RH (%),Z17_RH (%),Z1_RH (%),Z21_RH (%),Z22+23_RH (%),Z24_RH (%),Z25+26+27_RH (%),Z31_RH (%),Z32_RH (%),Z33_RH (%),Z3_RH (%),Z4_RH (%),Z5_RH (%)
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,41.523203,40.822198,41.204723,42.772116,40.271438,43.581602,41.344216,41.481117,42.470840,39.624603,40.377667,40.333220,43.192770,42.127690,44.416030
std,13.158781,13.544300,13.505271,12.427032,13.165171,13.504898,13.654681,11.479968,12.803962,12.015574,12.070100,12.082063,12.390486,12.922822,13.129294
min,22.797667,21.836667,22.367333,26.526909,20.124524,25.363000,22.266316,25.326000,25.129667,20.927167,23.923333,23.548334,25.316667,23.880000,24.746667
25%,29.686917,28.877166,29.089750,30.973250,28.875917,31.399500,29.285583,30.298917,30.961917,28.774250,29.179167,29.193250,31.799499,30.469999,32.566667
50%,37.836167,36.954500,37.825333,39.340333,35.918666,39.807167,37.784500,38.524167,39.188500,37.067167,37.436500,37.909167,39.898001,38.179000,41.006333
75%,52.667333,51.220500,51.413167,52.659833,50.733334,51.934333,50.388000,50.791333,51.101167,47.466833,50.243000,48.690667,55.040334,53.468500,56.002333
max,76.580000,78.077334,79.940000,75.641332,73.235999,79.522000,78.260000,69.974668,77.969334,74.507334,74.268000,73.824666,75.190666,72.568999,80.514666

In [4]:
df.isna().sum()

Timestamp           0
Z11_RH (%)          0
Z12+13_RH (%)       0
Z15+16_RH (%)       0
Z17_RH (%)          0
Z1_RH (%)           0
Z21_RH (%)          0
Z22+23_RH (%)       0
Z24_RH (%)          0
Z25+26+27_RH (%)    0
Z31_RH (%)          0
Z32_RH (%)          0
Z33_RH (%)          0
Z3_RH (%)           0
Z4_RH (%)           0
Z5_RH (%)           0
dtype: int64

In [5]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df = df.set_index('Timestamp')

C:\Users\Noble Adike\AppData\Local\Temp\ipykernel_17632\330094659.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [6]:
interpol = df.select_dtypes(include=['number']).columns

In [7]:
for col in interpol:
    df[col] = df[col].interpolate(limit=5, limit_direction='both').ffill().bfill()

In [8]:
df.isna().sum()

Z11_RH (%)          0
Z12+13_RH (%)       0
Z15+16_RH (%)       0
Z17_RH (%)          0
Z1_RH (%)           0
Z21_RH (%)          0
Z22+23_RH (%)       0
Z24_RH (%)          0
Z25+26+27_RH (%)    0
Z31_RH (%)          0
Z32_RH (%)          0
Z33_RH (%)          0
Z3_RH (%)           0
Z4_RH (%)           0
Z5_RH (%)           0
dtype: int64

In [9]:
df.head()

,Z11_RH (%),Z12+13_RH (%),Z15+16_RH (%),Z17_RH (%),Z1_RH (%),Z21_RH (%),Z22+23_RH (%),Z24_RH (%),Z25+26+27_RH (%),Z31_RH (%),Z32_RH (%),Z33_RH (%),Z3_RH (%),Z4_RH (%),Z5_RH (%)
Timestamp,,,,,,,,,,,,,,,
2023-06-01 00:00:00-04:00,42.966667,39.757667,34.861666,35.256667,41.540000,43.620000,41.435999,38.725333,43.431999,34.285334,33.121667,36.718333,36.933333,36.951000,40.076333
2023-06-01 01:00:00-04:00,44.112000,40.085001,35.441666,35.333667,41.760667,43.799334,42.823334,39.976333,43.982001,34.097000,32.688000,36.674000,37.158000,37.120667,40.878667
2023-06-01 02:00:00-04:00,43.748000,39.457000,35.754333,35.562333,41.676667,42.754000,41.169667,38.132333,42.231999,34.507666,33.974333,37.484000,35.858667,37.092000,41.272667
2023-06-01 03:00:00-04:00,43.278666,39.045666,35.993667,35.521000,41.206667,43.832000,41.967667,37.425333,43.048000,34.779666,33.649333,37.121000,35.761333,37.033667,40.719667
2023-06-01 04:00:00-04:00,42.915999,38.785333,36.200000,35.540666,40.190001,43.331332,42.117333,37.212334,42.993334,34.903667,33.632000,37.043333,35.786667,37.063667,40.464000