In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler

In [3]:
path = r"C:\Users\Noble Adike\Desktop\Coding\KPMG\kpmg-1a\data\harvard\Year 1 (Jun 2022 - May 2023)\RH_hourly\48190924_RH_hourly.csv"
df = pd.read_csv(path)
df.head()

,Timestamp,Z11_RH (%),Z12+13_RH (%),Z15+16_RH (%),Z17_RH (%),Z1_RH (%),Z21_RH (%),Z22+23_RH (%),Z24_RH (%),Z25+26+27_RH (%),Z31_RH (%),Z32_RH (%),Z33_RH (%),Z3_RH (%),Z4_RH (%),Z5_RH (%)
0,2022-06-01 00:00:00-04:00,45.215333,46.608666,47.192666,44.166666,49.378667,44.613333,43.268666,41.880666,44.026667,35.953333,38.271667,41.749333,47.582000,47.604667,51.721334
1,2022-06-01 01:00:00-04:00,44.751333,46.612000,47.588000,44.512667,48.980667,44.224000,43.379334,42.505333,43.670000,36.052333,38.213000,41.813333,47.142667,49.213334,52.044000
2,2022-06-01 02:00:00-04:00,43.614000,44.735334,46.026667,43.702000,48.008000,44.813333,44.601333,43.986666,45.272000,36.123000,38.156667,41.922000,45.159333,47.012000,50.065333
3,2022-06-01 03:00:00-04:00,42.936667,42.989334,45.080000,43.686000,43.716667,44.034667,43.841333,42.955666,45.464000,36.264333,38.210334,42.138000,45.010667,45.835334,49.455334
4,2022-06-01 04:00:00-04:00,42.430667,41.641333,44.600666,43.824666,42.423333,41.850000,41.242667,41.079334,43.147334,36.162333,37.711000,40.712667,45.510000,45.484667,50.216667

In [4]:
df.describe()

,Z11_RH (%),Z12+13_RH (%),Z15+16_RH (%),Z17_RH (%),Z1_RH (%),Z21_RH (%),Z22+23_RH (%),Z24_RH (%),Z25+26+27_RH (%),Z31_RH (%),Z32_RH (%),Z33_RH (%),Z3_RH (%),Z4_RH (%),Z5_RH (%)
count,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000,8589.000000
mean,39.771867,38.493650,39.312770,41.037314,38.355016,41.213911,39.365832,39.624629,40.221288,38.116472,38.429952,38.475026,40.105711,39.758490,43.581611
std,12.713064,12.232196,12.610202,11.807280,12.503670,12.065119,12.731104,10.692354,11.495939,11.449016,10.998580,11.053197,12.425646,12.391678,13.153015
min,15.140667,17.833666,19.352000,21.133333,16.020834,17.022250,15.949167,16.337833,15.546333,16.822667,20.875000,15.737833,20.726667,22.085000,21.655667
25%,28.374666,27.467667,27.892334,30.652333,27.250000,30.591000,28.173000,29.919333,29.877667,27.800333,28.773334,28.832333,28.360333,28.110667,30.508334
50%,35.626667,34.376667,34.217000,37.806666,33.411667,38.676667,35.556000,38.393333,37.553666,34.574001,35.258333,36.746334,36.450000,35.276665,39.969999
75%,50.366666,49.009334,50.488666,51.523333,49.494666,50.792666,49.264667,49.151333,49.146667,47.945333,47.830000,47.806666,51.464666,50.969333,55.554667
max,74.018000,69.480003,71.247334,69.536666,69.275333,75.263333,75.360001,67.908813,75.160004,72.492666,68.960000,69.396000,70.150000,68.360666,77.267334

In [5]:
df.isna().sum()

Timestamp             0
Z11_RH (%)          171
Z12+13_RH (%)       171
Z15+16_RH (%)       171
Z17_RH (%)          171
Z1_RH (%)           171
Z21_RH (%)          171
Z22+23_RH (%)       171
Z24_RH (%)          171
Z25+26+27_RH (%)    171
Z31_RH (%)          171
Z32_RH (%)          171
Z33_RH (%)          171
Z3_RH (%)           171
Z4_RH (%)           171
Z5_RH (%)           171
dtype: int64

In [6]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df = df.set_index('Timestamp')

C:\Users\Noble Adike\AppData\Local\Temp\ipykernel_13944\330094659.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [11]:
interpol = df.select_dtypes(include=['number']).columns

In [12]:
for col in interpol:
    df[col] = df[col].interpolate(limit=5, limit_direction='both').ffill().bfill()

In [13]:
df.isna().sum()

Z11_RH (%)          0
Z12+13_RH (%)       0
Z15+16_RH (%)       0
Z17_RH (%)          0
Z1_RH (%)           0
Z21_RH (%)          0
Z22+23_RH (%)       0
Z24_RH (%)          0
Z25+26+27_RH (%)    0
Z31_RH (%)          0
Z32_RH (%)          0
Z33_RH (%)          0
Z3_RH (%)           0
Z4_RH (%)           0
Z5_RH (%)           0
dtype: int64

In [14]:
df.head()

,Z11_RH (%),Z12+13_RH (%),Z15+16_RH (%),Z17_RH (%),Z1_RH (%),Z21_RH (%),Z22+23_RH (%),Z24_RH (%),Z25+26+27_RH (%),Z31_RH (%),Z32_RH (%),Z33_RH (%),Z3_RH (%),Z4_RH (%),Z5_RH (%)
Timestamp,,,,,,,,,,,,,,,
2022-06-01 00:00:00-04:00,45.215333,46.608666,47.192666,44.166666,49.378667,44.613333,43.268666,41.880666,44.026667,35.953333,38.271667,41.749333,47.582000,47.604667,51.721334
2022-06-01 01:00:00-04:00,44.751333,46.612000,47.588000,44.512667,48.980667,44.224000,43.379334,42.505333,43.670000,36.052333,38.213000,41.813333,47.142667,49.213334,52.044000
2022-06-01 02:00:00-04:00,43.614000,44.735334,46.026667,43.702000,48.008000,44.813333,44.601333,43.986666,45.272000,36.123000,38.156667,41.922000,45.159333,47.012000,50.065333
2022-06-01 03:00:00-04:00,42.936667,42.989334,45.080000,43.686000,43.716667,44.034667,43.841333,42.955666,45.464000,36.264333,38.210334,42.138000,45.010667,45.835334,49.455334
2022-06-01 04:00:00-04:00,42.430667,41.641333,44.600666,43.824666,42.423333,41.850000,41.242667,41.079334,43.147334,36.162333,37.711000,40.712667,45.510000,45.484667,50.216667