In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler

In [ ]:
path = r"C:\Users\Noble Adike\Desktop\Coding\KPMG\kpmg-1a\data\harvard\Year 1 (Jun 2022 - May 2023)\Zone_valve_hourly\48190957_Zone_Valve.csv"
df = pd.read_csv(path)

In [3]:
df.head()

,Timestamp,Z11_valve (%),Z12_valve (%),Z13_valve (%),Z14_valve (%),Z15_valve (%),Z16+17_valve (%),Z1_valve (%),Z21_valve (%),Z22_valve (%),Z23_valve (%),Z24_valve (%),Z25_valve (%),Z26_valve (%),Z27_valve (%),Z2_valve (%),Z3+4+5_valve (%),Z31_valve (%),Z32_valve (%),Z33_valve (%)
0,2022-06-01 00:00:00-04:00,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,0.0,100.0,100.0
1,2022-06-01 01:00:00-04:00,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,0.0,100.0,100.0
2,2022-06-01 02:00:00-04:00,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,0.0,100.0,100.0
3,2022-06-01 03:00:00-04:00,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,0.0,100.0,100.0
4,2022-06-01 04:00:00-04:00,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,0.0,100.0,100.0

In [4]:
df.describe()

,Z11_valve (%),Z12_valve (%),Z13_valve (%),Z14_valve (%),Z15_valve (%),Z16+17_valve (%),Z1_valve (%),Z21_valve (%),Z22_valve (%),Z23_valve (%),Z24_valve (%),Z25_valve (%),Z26_valve (%),Z27_valve (%),Z2_valve (%),Z3+4+5_valve (%),Z31_valve (%),Z32_valve (%),Z33_valve (%)
count,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000,8726.000000
mean,26.873145,22.541423,24.087811,25.471699,28.233094,25.772735,27.165884,25.044322,25.522623,25.047984,24.364739,26.037200,28.274543,26.674280,25.315435,21.359638,35.801204,25.849566,25.775228
std,39.239225,39.345226,39.148807,39.297735,39.021208,40.031217,39.947065,39.938371,39.736131,39.769842,39.631234,40.070866,38.840881,39.391704,37.903319,40.400148,46.330526,40.719321,39.772204
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.225000,0.000000,0.000000,0.000000,9.150000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.250000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,37.695833,19.212500,26.908333,36.566667,28.562500,36.058333,41.841667,36.787500,35.787500,34.145833,29.529167,40.958333,36.008333,38.229167,40.095833,0.000000,100.000000,42.783333,35.641667
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [5]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df = df.set_index('Timestamp')

C:\Users\Noble Adike\AppData\Local\Temp\ipykernel_23804\330094659.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [6]:
df.isna().sum()

Z11_valve (%)       34
Z12_valve (%)       34
Z13_valve (%)       34
Z14_valve (%)       34
Z15_valve (%)       34
Z16+17_valve (%)    34
Z1_valve (%)        34
Z21_valve (%)       34
Z22_valve (%)       34
Z23_valve (%)       34
Z24_valve (%)       34
Z25_valve (%)       34
Z26_valve (%)       34
Z27_valve (%)       34
Z2_valve (%)        34
Z3+4+5_valve (%)    34
Z31_valve (%)       34
Z32_valve (%)       34
Z33_valve (%)       34
dtype: int64

In [7]:
df.dropna(inplace=True)
df.isna().sum()

Z11_valve (%)       0
Z12_valve (%)       0
Z13_valve (%)       0
Z14_valve (%)       0
Z15_valve (%)       0
Z16+17_valve (%)    0
Z1_valve (%)        0
Z21_valve (%)       0
Z22_valve (%)       0
Z23_valve (%)       0
Z24_valve (%)       0
Z25_valve (%)       0
Z26_valve (%)       0
Z27_valve (%)       0
Z2_valve (%)        0
Z3+4+5_valve (%)    0
Z31_valve (%)       0
Z32_valve (%)       0
Z33_valve (%)       0
dtype: int64